[2022-12-26T12:40:13.712+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_cloud.upload_file_to_gcs manual__2022-01-01T08:41:01+00:00 [queued]>
[2022-12-26T12:40:13.719+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_cloud.upload_file_to_gcs manual__2022-01-01T08:41:01+00:00 [queued]>
[2022-12-26T12:40:13.719+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T12:40:13.720+0000] {taskinstance.py:1284} INFO - Starting attempt 10 of 10
[2022-12-26T12:40:13.721+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T12:40:13.729+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): upload_file_to_gcs> on 2022-01-01 08:41:01+00:00
[2022-12-26T12:40:13.736+0000] {standard_task_runner.py:55} INFO - Started process 647 to run task
[2022-12-26T12:40:13.740+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_cloud', 'upload_file_to_gcs', 'manual__2022-01-01T08:41:01+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpfw_4szqi']
[2022-12-26T12:40:13.742+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask upload_file_to_gcs
[2022-12-26T12:40:13.797+0000] {task_command.py:389} INFO - Running <TaskInstance: data_ingestion_to_cloud.upload_file_to_gcs manual__2022-01-01T08:41:01+00:00 [running]> on host 630310be3161
[2022-12-26T12:40:13.846+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_cloud
AIRFLOW_CTX_TASK_ID=upload_file_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T08:41:01+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-01T08:41:01+00:00
[2022-12-26T12:40:13.857+0000] {logging_mixin.py:137} INFO - ['yellow_tripdata_2022-1.parquet']
[2022-12-26T12:40:13.871+0000] {logging_mixin.py:137} INFO - <Bucket: datalake-zoomcamp-terraform>
[2022-12-26T12:40:13.874+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion.py", line 37, in upload_file_to_gcs
    blob.upload_from_filename(f'/opt/airflow/data/{filename}')
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2681, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: "/opt/airflow/data/['yellow_tripdata_2022-1.parquet']"
[2022-12-26T12:40:13.878+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_ingestion_to_cloud, task_id=upload_file_to_gcs, execution_date=20220101T084101, start_date=20221226T124013, end_date=20221226T124013
[2022-12-26T12:40:13.884+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task upload_file_to_gcs ([Errno 2] No such file or directory: "/opt/airflow/data/['yellow_tripdata_2022-1.parquet']"; 647)
[2022-12-26T12:40:13.912+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-26T12:40:13.926+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
